WIP: Initial support for X-Forward-For
vernemq/vernemq pull request #2120
Opened 2023-03-19 21:56 UTC by mths1

Initial support for X-Forward-For  header. Currently, only works for Websockets (MQTTWS). To turn on support for X-Forward-Header you need to set

- listener.ws.$name.proxy_xff_support on
- istener.ws.$name.proxy_xff_trusted_intermediate IP1;IP2;...

where IP1... are acceptable proxy IPs. Support for vmq_http_pub plugin will follow (amazing how many changes this small plugin triggers lately) :-)

Related Issues:
#1754 
#1783 
(among others)

This is WiP, as I do not have a test lab for all kinds of proxies any help (testers) is appreciated. The code will print some debug information that will help in case something breaks. 

## Proposed Changes

Adds support for X-Forward-For header.

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes issue #XXXX)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, styles...)
- [ ] DevOps (Build scripts, pipelines...)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask on the
mailing list. We're here to help! This is simply a reminder of what we are
going to look for before merging your code._

- [ ] I have read the [CODE_OF_CONDUCT.md](https://github.com/vernemq/vernemq/blob/main/CODE_OF_CONDUCT.md) document
- [ ] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if needed)
- [ ] Any dependent changes have been merged and published in related repositories
- [ ] I have updated changelog (At the bottom of the release version)
- [ ] I have squashed all my commits into one before merging

## Further Comments

If this is a relatively large or complex change, kick off the discussion by
explaining why you chose the solution you did and what alternatives you
considered, etc.

2023-03-25 14:39 UTC, mths1 commented
How to proceed with this one? I have the feeling letting it in the WiP state will not help :-) It works for my nginx use case, but to get this more stable it needs to be tested with more setups.

2023-03-25 16:03 UTC, ioolkos commented
@mths1 please leave it as Draft for now, so that I can test at least HAProxy. (after that we can take out the test info logs).
Also, even if it turns out to be only useful/working on NGINX, it'd still be a valuable contribution, precisely because NGINX is missing a full proxy protocol implementation at the outgoing side.

2023-05-03 11:25 UTC, mths1 commented
@ioolkos : Any news on this? I'd have some time this week to "get stuff done".

2023-05-03 12:01 UTC, ioolkos commented
@mths1 ah, yes, I promised to check this on HAProxy... need to find the hour to do this.
Other than that, the PR seems to look complete, so feel free to promote it from draft status.

2023-05-03 19:12 UTC, ioolkos commented
@mths1 on a first quick test this doesn't seem to work on HAProxy yet.

Can you show the exact client side request you use for NGINX?

2023-05-04 07:50 UTC, ioolkos commented
Ok, I can establish a WS connection over HAProxy, with a config as below. Haven't yet checked further details.

in `haproxy.cfg`:

```
frontend vernemq_ws_frontend_xff
        bind 127.0.0.1:9113 name http1
	mode http
        default_backend vernemq_ws_backend_xff
        
backend vernemq_ws_backend_xff
	option http-server-close
	option forwardfor
	mode http
   	timeout tunnel 1h
        server mqtt1 127.0.0.1:7779 check
```

in `vernemq.conf`:
```
listener.ws.xfftest = 127.0.0.1:7779
listener.ws.xfftest.proxy_xff_support = on
listener.ws.xfftest.proxy_xff_trusted_intermediate = 127.0.0.1
```

2023-05-04 08:00 UTC, mths1 commented
@ioolkos : Great! My nginx test was quite similar (and thus quite basic). I see some reproducible error in the vmq_connect_suite which I will look into.

2023-05-08 23:07 UTC, ioolkos commented
@mths1 You mentioned an error in the connect_suite. Were you able to resolve that? if yes, I think in terms of the feature, we can go with what we have here.

2023-05-11 19:04 UTC, ioolkos commented on apps/vmq_server/src/vmq_ranch_config.erl
> +    lager:info("My opts ~p~n", [Opts]),
to remove

2023-05-11 19:04 UTC, ioolkos commented on apps/vmq_server/src/vmq_websocket.erl
> +    lager:info("Options ~p~n", [Opts]),
to remove

2023-05-11 19:05 UTC, ioolkos requested changes
A couple logs to remove, then we merge the feature.

2023-05-12 11:51 UTC, merged